### PR TITLE
Translation review and minor adjustmets

### PR DESCRIPTION
**Pull request by ENOANO**
Review and minor adjustments on the Brazilian Portuguese version of Store_Description.txt and Store-Subtitle.txt

### CODE REVIEW

**Comment by NickAtGit** [comment]
@ENOANO I merged it, looks good to me. Thanks

**Comment by NickAtGit** [comment]
@ENOANO Is there any way I can give you some promo codes in private? Do you have twitter?

**Comment by ENOANO** [comment]
I am glad to help!
I do have Twitter, but I had to make it private months ago. I don't mind if you follow me, though. Just tell me yours and I'll try to send you a DM.
Also, I think I could come up with Spanish and Italian translations. What do you think?

**Comment by NickAtGit** [comment]
`Also, I think I could come up with Spanish and Italian translations. What do you think?`
That would be awesome!!!

Send me a message over here ;)
https://twitter.com/N1C0_MUC

**Pull request merged**
